version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/medappeals
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=medicare_appeals_dev  # This creates our initial database.
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: