APPEAL_LEVEL = (
    ('level 1', 'Level 1'),
    ('level 2', 'Level 2'),
    ('level 3', 'Level 3'),
    ('level 4', 'Level 4'),
)

APPEAL_SERVICE_CATEGORY = (
    ('practitioner services', 'Practitioner Services'),
    ('emergency room', 'Emergency Room'),
    ('acute inpatient hospital', 'Acute Inpatient Hospital'),
    ('office-based lab/x-ray', 'Office-based Lab/X-ray'),
    ('nursing home', 'Nursing Home'),
    ('outpatient therapies/corf', 'Outpatient Therapies/CORF'),
    ('ground transportation', 'Ground Transportation'),
    ('home health', 'Home Health'),
    ('hospice', 'Hospice'),
    ('non-medicare benefit', 'Non-Medicare Benefit'),
    ('out of area', 'Out of Area'),
    ('skilled nursing facility', 'Skilled Nursing Facility'),
    ('air ambulance', 'Air Ambulance'),
    ('pathology/laboratory', 'Pathology/Laboratory'),
    ('imaging/radiology', 'Imaging/Radiology'),
    ('drugs', 'Drugs'),
    ('vision services', 'Vision Services'),
    ('chiropractic', 'Chiropractic'),
    ('dental', 'Dental'),
    ('ac dismissal', 'AC Dismissal'),
    ('outpatient hospital/asc', 'Outpatient Hospital/ASC'),
    ('acute inpatient rehab', 'Acute Inpatient Rehab.'),
    ('acute inpatient psych', 'Acute Inpatient Psych'),
    ('outpatient psych/com mental health', 'Outpatient Psych/Com Mental Health'),
    ('partial psych hosp', 'Partial Psych Hosp'),
    ('intermediate care', 'Intermediate Care'),
    ('long term care hospital', 'Long Term Care Hospital'),
    ('rural health clinic/fqhc', 'Rural Health Clinic/FQHC'),
    ('srd facility', 'SRD Facility'),
    ('other', 'Other'),
    ('medical/surgical supplies', 'Medical/Surgical Supplies'),
    ('hosp bed & support surfaces', 'Hosp Bed & Support Surfaces'),
    ('oxygen', 'Oxygen'),
    ('manual wheelchairs', 'Manual Wheelchairs'),
    ('miscellaneous dmepos', 'Miscellaneous DMEPOS'),
    ('orthoses', 'Orthoses'),
    ('drugs miscellaneous', 'Drugs Miscellaneous'),
    ('enteral/parenteral nutrition', 'Enteral/Parenteral Nutrition'),
    ('glucose monitors', 'Glucose Monitors'),
    ('office e/m services', 'Office E/M Services'),
    ('hospital e/m services', 'Hospital E/M Services'),
    ('facility e/m: snf/asst/home', 'Facility E/M: SNF/Asst/Home'),
    ('integum/musc-skeletal sur', 'Integum/musc-skeletal Sur'),
    ('respiratory/cardiovsclr sur', 'Respiratory/Cardiovsclr Sur'),
    ('nervous system surgery', 'Nervous System Surgery'),
    ('gastro./urinary/genital sur', 'Gastro./Urinary/Genital Sur'),
    ('other surgery', 'Other Surgery'),
    ('anesthesia', 'Anesthesia'),
    ('podiatry', 'Podiatry'),
    ('radiation/chemo/infusion', 'Radiation/Chemo/Infusion'),
    ('audiology', 'Audiology'),
    ('idtf', 'IDTF'),
    ('technical denial', 'Technical Denial'),
    ('msp', 'MSP'),
    ('copay/deductible', 'Copay/Deductible'),
    ('eligibility', 'Eligibility'),
    ('consolidated billing', 'Consolidated Billing'),
    ('infusion pumps', 'Infusion Pumps'),
    ('nebulizers & drugs', 'Nebulizers & Drugs'),
    ('prostheses', 'Prostheses'),
    ('ostomy & urological', 'Ostomy & Urological'),
    ('pos. airway pressure device', 'Pos. Airway Pressure Device'),
    ('neg. pressure wound therapy', 'Neg. Pressure Wound Therapy'),
    ('pneumatic compressor', 'Pneumatic compressor'),
    ('repairs', 'Repairs'),
    ('respiratroy-miscellaneous', 'Respiratroy-Miscellaneous'),
    ('surgical dressings', 'Surgical Dressings'),
    ('therapeutic shoes', 'Therapeutic Shoes'),
)

APPEAL_STATUS = (
    ('closed', 'Closed'),
    ('open', 'Open'),
    ('promoted', 'Promoted'),
    ('received', 'Received'),
    ('reopened', 'Reopened'),
)

APPEAL_STATUS_DEFAULT = 'received'

APPEAL_STATUS_OUTCOME = (
    ('dismissal', 'Dismissal'),
    ('general', 'General'),
    ('misfiled', 'Misfiled'),
    ('misrouted', 'Misrouted'),
    ('no count', 'No Count/Inquiry'),
    ('favorable', 'Favorable for Appellant'),
    ('unfavorable', 'Unfavorable for Appellant'),
    ('partially favorable', 'Partially favorable for Appellant'),
)

APPEAL_WORKFLOW_TYPE = (
    ('dismissal', 'Dismissal'),
    ('general', 'General'),
    ('misfiled', 'Misfiled'),
    ('mirouted', 'Misrouted'),
    ('no count', 'No Count/Inquiry'),
)

APPEAL_WORKFLOW_TYPE_DEFAULT = 'general'

MEDICARE_PART = (
    ('522 lcd','522-LCD'),
    ('entitlement', 'Entitlement'),
    ('ffs part a', 'FFS-Part A only'),
    ('ffs part b only', 'FFS-Part B only'),
    ('ffs part b of a', 'FFS-Part B of A'),
    ('mc cost', 'MC-COST'),
    ('mc hcpp', 'MC-HCPP'),
    ('mc ma organization', 'MC-MA Organization (MAO)'),
    ('mc pace', 'MC-PACE'),
    ('part a', 'Part A'),
    ('part b', 'Part B'),
    ('part c', 'Part C'),
    ('part d', 'Part D'),
    ('part b irmaa', 'Part B IRMAA'),
    ('part d irmaa', 'Part D IRMAA'),
)

PLACE_OF_SERVICE = (
    ('pharmacy', 'Pharmacy'),
    ('school', 'School'),
    ('homeless shelter', 'Homeless Shelter'),
    ('indian free-standing fac', 'Indian Free-Standing Fac'),
    ('indian provider facility', 'Indian Provider Facility'),
    ('tribal 638 free-standing fac', 'Tribal 638 Free-Standing Fac'),
    ('tribal 638 provider facility', 'Tribal 638 Provider Facility'),
    ('prison/correctional facility', 'Prison/Correctional Facility'),
    ('office', 'Office'),
    ('home', 'Home'),
    ('assisted living facility', 'Assisted Living Facility'),
    ('group home', 'Group Home'),
    ('mobile unit', 'Mobile Unit'),
    ('urgent care facility', 'Urgent Care Facility'),
    ('inpatient hospital', 'Inpatient Hospital'),
    ('outpatient hospital ', 'Outpatient Hospital '),
    ('emergency room - hospital', 'Emergency Room - Hospital'),
    ('ambulatory surgical center', 'Ambulatory Surgical Center'),
    ('brithing center', 'Brithing Center'),
    ('military treatment facility', 'Military Treatment Facility'),
    ('skilled nursing facility', 'Skilled Nursing Facility'),
    ('nursing facility', 'Nursing Facility'),
    ('custodial care facility', 'Custodial Care Facility'),
    ('hospice', 'Hospice'),
    ('ambulance - land', 'Ambulance - Land'),
    ('ambulance - air or water', 'Ambulance - Air or Water'),
    ('independent clinic', 'Independent Clinic'),
    ('fed qualified health center', 'Fed Qualified Health Center'),
    ('inpatient psychiatric facility', 'Inpatient Psychiatric Facility'),
    ('psych facility - part. hosp.', 'Psych Facility - Part. Hosp.'),
    ('community mental health center', 'Community Mental Health Center'),
    ('intr care facility/intellectual disability', 'Intr Care Facility/Intellectual Disability'),
    ('res sub abuse treatment facility', 'Res Sub Abuse Treatment Facility'),
    ('psych res treatment center', 'Psych Res Treatment Center'),
    ('non res sub abuse treat facility', 'Non Res Sub Abuse Treat Facility'),
    ('mass immunization center', 'Mass Immunization Center'),
    ('comp. inpatient rehab facility', 'Comp. Inpatient Rehab Facility'),
    ('comp. outpatient rehab facility', 'Comp. Outpatient Rehab Facility'),
    ('eng-stg renal dis treat facility', 'Eng-Stg Renal Dis Treat Facility'),
    ('public health clinic', 'Public Health Clinic'),
    ('rural health clinic', 'Rural Health Clinic'),
    ('independent laboratory', 'Independent Laboratory'),
    ('other place of service', 'Other Place of Service'),
)

PROVIDER_TYPE = (
    ('ambulance', 'Ambulance'),
    ('ambulatory surgical center', 'Ambulatory surgical Center'),
    ('anesthesia assistant', 'Anesthesia Assistant'),
    ('audiologist', 'Audiologist'),
    ('chiropractor', 'Chiropractor'),
    ('clinical psychologist', 'Clinical Psychologist'),
    ('clinical social worker', 'Clinical Social Worker'),
    ('community mental h. ctr', 'Community Mental H. Ctr'),
    ('corf', 'CORF'),
    ('dentist', 'Dentist'),
    ('durable med eqp. dealer', 'Durable Med Eqp. Dealer'),
    ('free standing clinic', 'Free Standing Clinic'),
    ('free-standing birthing center', 'Free-Standing Birthing Center'),
    ('h. based indp renal dia. ctr', 'H. Based Indp Renal Dia. Ctr'),
    ('home health agency', 'Home Health Agency'),
    ('hospice', 'Hospice'),
    ('hospital', 'Hospital'),
    ('hospital emergency room', 'Hospital Emergency Room'),
    ('hospital outpatient department', 'Hospital Outpatient Department'),
    ('independent laboratory', 'Independent laboratory'),
    ('indp diag. test facility', 'Indp Diag. Test Facility'),
    ('mammography screening center', 'Mammography Screening Center'),
    ('mco', 'MCO'),
    ('med doctor (md, osteopath)', 'Med Doctor (MD, Osteopath)'),
    ('medical supplies dealer', 'Medical Supplies Dealer'),
    ('nurse', 'Nurse'),
    ('occupational therapist', 'Occupational Therapist'),
    ('optician ', 'Optician '),
    ('optometrist', 'Optometrist'),
    ('outpatient rehab facility', 'Outpatient Rehab Facility'),
    ('pharmacy', 'Pharmacy'),
    ('physical therapist', 'Physical Therapist'),
    ('physician assistant', 'Physician Assistant'),
    ('podiatrist', 'Podiatrist'),
    ('pub health/welfare agency', 'Pub Health/Welfare Agency'),
    ('registered dietician', 'Registered Dietician'),
    ('respiratory therapist', 'Respiratory Therapist'),
    ('rural health clinic', 'Rural Health Clinic'),
    ('skilled nursing facility', 'Skilled Nursing Facility'),
    ('speech language pathologist', 'Speech Language Pathologist'),
    ('other', 'Other'),
)

REQUESTOR_TYPE = (
    ('aor', 'AOR'),
    ('non-contract provider', 'Non-Contract Provider'),
    ('advocacy group', 'Advocacy Group'),
    ('appointed representative', 'Appointed Representative'),
    ('attorney', 'Attorney'),
    ('beneficiary', 'Beneficiary'),
    ('congress member', 'Congress Member'),
    ('estate', 'Estate'),
    ('family', 'Family'),
    ('part d plan', 'Part D Plan'),
    ('prescribing physician', 'Prescribing Physician'),
    ('provider', 'Provider'),
    ('state medicaid agency', 'State Medicaid Agency'),
    ('other', 'Other'),
)
