APPEAL_LEVEL = (('lvl1', 'Level 1'), ('lvl2', 'Level 2'), ('lvl3', 'Level 3'),
                ('lvl4', 'Level 4'))

APPEAL_SERVICE_CATEGORY = (
    ('01', 'Practitioner Services'),
    ('02', 'Emergency Room'),
    ('03', 'Acute Inpatient Hospital'),
    ('04', 'Office-based Lab/X-ray'),
    ('05', 'Nursing Home'),
    ('06', 'Outpatient Therapies/CORF'),
    ('07', 'Ground Transportation'),
    ('08', 'Home Health'),
    ('11', 'Hospice'),
    ('12', 'Non-Medicare Benefit'),
    ('21', 'Out of Area'),
    ('24', 'Skilled Nursing Facility'),
    ('26', 'Air Ambulance'),
    ('30', 'Pathology/Laboratory'),
    ('31', 'Imaging/Radiology'),
    ('32', 'Drugs'),
    ('33', 'Vision Services'),
    ('34', 'Chiropractic'),
    ('35', 'Dental'),
    ('39', 'AC Dismissal'),
    ('41', 'Outpatient Hospital/ASC'),
    ('42', 'Acute Inpatient Rehab.'),
    ('43', 'Acute Inpatient Psych'),
    ('44', 'Outpt Psych/Com Mental Hlth'),
    ('45', 'Partial Psych Hosp'),
    ('46', 'Intermediate Care'),
    ('47', 'Long Term Care Hospital'),
    ('48', 'Rurla Health Clinic/FQHC'),
    ('49', 'SRD Facility'),
    ('50', 'Other'),
    ('51', 'Medical/Surgical Supplies'),
    ('52', 'Hosp Bed & Support Surfaces'),
    ('53', 'Oxygen'),
    ('54', 'Manual Wheelchairs'),
    ('55', 'Miscellaneous DMEPOS'),
    ('56', 'Orthoses'),
    ('57', 'Drugs Miscellaneous'),
    ('58', 'Enteral/Parenteral Nutri.'),
    ('59', 'Glucose Monitors'),
    ('60', 'Office E/M Services'),
    ('61', 'Hospital E/M Services'),
    ('62', 'Facility E/M: SNF/Asst/Home'),
    ('65', 'Integum/musc-skeletal Sur'),
    ('66', 'Respiratory/Cardiovsclr Sur'),
    ('67', 'Nervous System Surgery'),
    ('68', 'Gastro./Urinary/Genital Sur'),
    ('69', 'Other Surgery'),
    ('70', 'Anesthesia'),
    ('71', 'Podiatry'),
    ('72', 'Radiation/Chemo/Infusion'),
    ('73', 'Audiology'),
    ('74', 'IDTF'),
    ('79', 'Technical Denial'),
    ('80', 'MSP'),
    ('81', 'Copay/Deductible'),
    ('82', 'Eligibility'),
    ('83', 'Consolidated Billing'),
    ('84', 'Infustion Pumps'),
    ('85', 'Nebulizers & Drugs'),
    ('87', 'Prostheses'),
    ('88', 'Ostomy & Urological'),
    ('89', 'Pos. Airway Pressure Device'),
    ('90', 'Neg. Pressure Wound Therapy'),
    ('91', 'Pneumatic compressor'),
    ('92', 'Repairs'),
    ('93', 'Respiratroy-Miscellaneous'),
    ('94', 'Surgical Dressings'),
    ('95', 'Therapeutic Shoes'),
)

APPEAL_STATUS = (('o', 'Open'), ('c', 'Closed'), ('p', 'Promoted'),
                 ('r', 'Reopened'))

APPEAL_STATUS_DEFAULT = 'o'

APPEAL_WORKFLOW_TYPE = (
    ('d', 'Dismissal'),
    ('g', 'General'),
    ('mf', 'Misfiled'),
    ('mr', 'Misrouted'),
    ('nc', 'No Count/Inquiry'),
)

APPEAL_WORKFLOW_TYPE_DEFAULT = 'g'

MEDICARE_PART = (('e', 'Entitlement'), ('ffsa', 'FFS-Part A only'),
                 ('ffsb', 'FFS-Part B only'), ('d', 'Part D'),
                 ('ffsba', 'FFS-Part B of A'), ('mccost', 'MC-COST'),
                 ('mchcpp', 'MC-HCPP'), ('mcma', 'MC-MA Organization (MAO)'),
                 ('mcpace',
                  'MC-PACE'), ('553lcs',
                               '522-LCD'), ('birmaa',
                                            'Part B IRMAA'), ('dirmma',
                                                              'Part D IRMAA'))

PLACE_OF_SERVICE = (
    ('01', 'Pharmacy'), ('03', 'School'), ('04', 'Homeless Shelter'),
    ('05', 'Indian Free-Standing Fac'), ('06', 'Indian Provider Facility'),
    ('07', 'Tribal 638 Free-Stand. Fac'), ('08', 'Tribal 638 Provd Facility'),
    ('09', 'Prison/correcl Facility'), ('11', 'Office'), ('12', 'Home'),
    ('13', 'Assisted Living Facility'), ('14', 'Group Home'), ('15',
                                                               'Mobile Unit'),
    ('20',
     'Urgent Care Facility'), ('21',
                               'Inpatient Hospital'), ('22',
                                                       'Outpatient Hospital '),
    ('23', 'Emergency Room - Hospital'), ('24', 'Ambulatory Surgical Center'),
    ('25', 'Brithing Center'), ('26', 'Miliatry Treatment Facility'),
    ('31', 'Skilled Nursing Facility'), ('32', 'Nursing Facility'),
    ('33', 'Custodial Care Facility'), ('34',
                                        'Hospice '), ('41',
                                                      'Ambulance - Land'),
    ('42', 'Ambulance - Air or Water'), ('49', 'Independent Clinic'),
    ('50', 'Fed Qualified Health Center'), ('51', 'Inpatient Psychiatric Fac'),
    ('52', 'Psych Fac - Part. Hosp.'), ('53', 'Community Mental Health Ctr'),
    ('54', 'Intr Care Fac/Mental Retard'), ('55',
                                            'Res Sub Abuse Treatment Fac'),
    ('56', 'Psych Res Treatment Center'), ('57',
                                           'Non Res Sub Abuse Treat Fac'),
    ('60', 'Mass Immunization Center'), ('61', 'Comp. Inpatient Rehab Fac'),
    ('62', 'Comp. Outpatient Rehab Fac'), ('65',
                                           'Eng-Stg Renal Dis Treat Fac'),
    ('71', 'Public Health Clinic'), ('72', 'Rural Health Clinic'),
    ('81', 'Independent Laboratory'), ('99', 'Other Place of Service'))

REQUESTOR_TYPE = (('aor',
                   'AOR'), ('ncprovider',
                            'Non-Contract Provider'), ('ag', 'Advocacy Group'),
                  ('ar', 'Appointed Rep'), ('a', 'Attorney'), ('b',
                                                               'Beneficfiary'),
                  ('cm', 'Congress Member'), ('e', 'Estate'), ('f', 'Family'),
                  ('partd', 'Part D Plan'), ('pp', 'Prescribing Physician'),
                  ('provider',
                   'Provider'), ('sma', 'State Medicaid Agency'), ('o',
                                                                   'Other'))
