# Generated by Django 2.0.13 on 2019-03-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HollisticAppeal',
            new_name='HolisticAppeal',
        ),
        migrations.RenameField(
            model_name='appeal',
            old_name='hollistic_appeal',
            new_name='holistic_appeal',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='hollistic_appeal',
            new_name='holistic_appeal',
        ),
        migrations.AlterModelTable(
            name='holisticappeal',
            table='holistic_appeal',
        ),
    ]
