# Generated by Django 2.0.13 on 2019-06-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_auto_20190305_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='rac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeals.Appeal'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
